import { CliTool, IdeExtension, IdePlatform } from '@/types';

// IDE Extensions that can be installed across multiple IDEs
export const IDE_EXTENSIONS: IdeExtension[] = [
  {
    id: 'amp-extension',
    name: 'Amp',
    icon: '⚡',
    docsUrl: 'https://ampcode.com/manual',
    description: "Sourcegraph's AI coding agent extension",
    settingsPrefix: 'amp',
    suggestedSettings: [
      {
        label: 'MCP Servers',
        jsonPath: 'mcpServers',
        icon: '🔌',
        description: 'MCP server configuration',
      },
      {
        label: 'Permissions',
        jsonPath: 'permissions',
        icon: '🔒',
        description: 'Tool permissions configuration',
      },
    ],
  },
];

// IDE Platforms with extension support
export const IDE_PLATFORMS: IdePlatform[] = [
  {
    id: 'vscode',
    name: 'VS Code',
    icon: '💻',
    docsUrl: 'https://code.visualstudio.com/docs/configure/settings',
    description: 'Visual Studio Code',
    settingsPaths: {
      linux: '~/.config/Code/User/settings.json',
      macos: '~/Library/Application Support/Code/User/settings.json',
      windows: '%APPDATA%/Code/User/settings.json',
    },
    extensions: [
      {
        extensionId: 'amp-extension',
        label: 'Amp Extension',
        jsonPathPrefix: 'amp',
        icon: '⚡',
        description: 'Amp AI coding agent settings',
      },
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: '▢',
    docsUrl: 'https://cursor.com/docs',
    description: 'AI-first code editor (VS Code fork)',
    settingsPaths: {
      linux: '~/.config/Cursor/User/settings.json',
      macos: '~/Library/Application Support/Cursor/User/settings.json',
      windows: '%APPDATA%/Cursor/User/settings.json',
    },
    extensions: [
      {
        extensionId: 'amp-extension',
        label: 'Amp Extension',
        jsonPathPrefix: 'amp',
        icon: '⚡',
        description: 'Amp AI coding agent settings',
      },
    ],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    icon: '🏄',
    docsUrl: 'https://docs.windsurf.com/',
    description: 'AI-native IDE by Codeium',
    settingsPaths: {
      linux: '~/.config/Windsurf/User/settings.json',
      macos: '~/Library/Application Support/Windsurf/User/settings.json',
      windows: '%APPDATA%/Windsurf/User/settings.json',
    },
    extensions: [
      {
        extensionId: 'amp-extension',
        label: 'Amp Extension',
        jsonPathPrefix: 'amp',
        icon: '⚡',
        description: 'Amp AI coding agent settings',
      },
    ],
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    icon: '🚀',
    docsUrl: 'https://antigravity.google/',
    description: 'Google\'s agent-first development platform',
    settingsPaths: {
      linux: '~/.config/Antigravity/User/settings.json',
      macos: '~/Library/Application Support/Antigravity/User/settings.json',
      windows: '%APPDATA%/Antigravity/User/settings.json',
    },
    extensions: [
      {
        extensionId: 'amp-extension',
        label: 'Amp Extension',
        jsonPathPrefix: 'amp',
        icon: '⚡',
        description: 'Amp AI coding agent settings',
      },
    ],
  },
];

export const CLI_TOOLS: CliTool[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    icon: '🤖',
    docsUrl: 'https://code.claude.com/docs/en/settings',
    description: "Anthropic's official Claude Code CLI",
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.claude/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'User settings (permissions, env, hooks, model)',
      },
      {
        label: 'MCP Servers (User)',
        path: '~/.claude.json',
        format: 'json',
        icon: '🔌',
        description: 'User-level MCP server configuration',
        jsonPath: 'mcpServers',
      },
      {
        label: 'MCP Servers (Project)',
        path: '.mcp.json',
        format: 'json',
        icon: '📁',
        description: 'Project-level MCP server configuration',
      },
      {
        label: 'Memory',
        path: '~/.claude/CLAUDE.md',
        format: 'md',
        icon: '📝',
        description: 'Global instructions/memory file',
      },
    ],
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    icon: '✨',
    docsUrl: 'https://geminicli.com/docs/',
    description: "Google's Gemini CLI",
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.gemini/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'Main settings with MCP servers',
      },
      {
        label: 'Memory',
        path: '~/.gemini/GEMINI.md',
        format: 'md',
        icon: '📝',
        description: 'Global context/memory file',
      },
    ],
  },

  {
    id: 'amp',
    name: 'Amp',
    icon: '⚡',
    docsUrl: 'https://ampcode.com/manual',
    description: "Sourcegraph's AI coding agent",
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.config/amp/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'Main configuration file (MCP servers, permissions, tools)',
      },
      {
        label: 'MCP Servers',
        path: '~/.config/amp/settings.json',
        format: 'json',
        icon: '🔌',
        description: 'MCP server configuration',
        jsonPath: 'amp.mcpServers',
      },
      {
        label: 'Permissions',
        path: '~/.config/amp/settings.json',
        format: 'json',
        icon: '🔒',
        description: 'Tool permissions configuration',
        jsonPath: 'amp.permissions',
      },
      {
        label: 'Workspace Settings',
        path: '.amp/settings.json',
        format: 'json',
        icon: '📁',
        description: 'Project-level Amp settings',
      },
      {
        label: 'AGENTS.md (Global)',
        path: '~/.config/amp/AGENTS.md',
        format: 'md',
        icon: '📝',
        description: 'Global agent instructions/memory',
      },
      {
        label: 'AGENTS.md (Config)',
        path: '~/.config/AGENTS.md',
        format: 'md',
        icon: '📝',
        description: 'Alternative global agent instructions',
      },
    ],
  },
  {
    id: 'gh-copilot',
    name: 'GitHub Copilot CLI',
    icon: '🐙',
    docsUrl: 'https://docs.github.com/en/copilot/how-tos/use-copilot-agents/use-copilot-cli',
    description: "GitHub's agentic AI coding assistant for the terminal",
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.copilot/config.json',
        format: 'json',
        icon: '⚙️',
        description: 'Main configuration (trusted folders, preferences)',
      },
      {
        label: 'MCP Servers',
        path: '~/.copilot/mcp-config.json',
        format: 'json',
        icon: '🔌',
        description: 'MCP server configuration',
        jsonPath: 'servers',
      },
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    icon: '▢',
    docsUrl: 'https://cursor.com/docs',
    description: 'AI-first code editor',
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.config/Cursor/User/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'User settings file',
      },
    ],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    icon: '⌬',
    docsUrl: 'https://opencode.ai/docs/config/',
    description: 'AI coding agent for the terminal by SST',
    suggestedConfigs: [
      {
        label: 'Global Config',
        path: '~/.config/opencode/opencode.json',
        format: 'json',
        icon: '⚙️',
        description: 'Global configuration (theme, model, providers, MCP)',
      },
      {
        label: 'Project Config',
        path: 'opencode.json',
        format: 'json',
        icon: '📁',
        description: 'Project-level configuration',
      },
      {
        label: 'MCP Servers',
        path: '~/.config/opencode/opencode.json',
        format: 'json',
        icon: '🔌',
        description: 'MCP server configuration',
        jsonPath: 'mcp',
      },
      {
        label: 'Auth Credentials',
        path: '~/.local/share/opencode/auth.json',
        format: 'json',
        icon: '🔑',
        description: 'Provider API keys and credentials',
      },
      {
        label: 'MCP OAuth Tokens',
        path: '~/.local/share/opencode/mcp-auth.json',
        format: 'json',
        icon: '🔐',
        description: 'OAuth tokens for MCP servers',
      },
    ],
  },
  {
    id: 'droid',
    name: 'Factory Droid CLI',
    icon: '🤖',
    docsUrl: 'https://docs.factory.ai/cli/configuration/settings',
    description: 'AI coding agent for terminal',
    suggestedConfigs: [
      {
        label: 'Settings',
        path: '~/.factory/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'Droid CLI settings and preferences',
      },
      {
        label: 'MCP Servers',
        path: '~/.factory/mcp.json',
        format: 'json',
        icon: '🔌',
        description: 'MCP (Model Context Protocol) servers',
        jsonPath: 'mcpServers',
      },
    ],
  },
  {
    id: 'qwen-code',
    name: 'Qwen Code',
    icon: '🐦',
    docsUrl: 'https://qwenlm.github.io/qwen-code-docs/en/users/overview',
    description: "Alibaba's AI coding agent CLI",
    suggestedConfigs: [
      {
        label: 'Settings (User)',
        path: '~/.qwen/settings.json',
        format: 'json',
        icon: '⚙️',
        description: 'Main user configuration',
      },
      {
        label: 'Settings (Project)',
        path: '.qwen/settings.json',
        format: 'json',
        icon: '📁',
        description: 'Project-level configuration',
      },
      {
        label: 'MCP Servers',
        path: '~/.qwen/settings.json',
        format: 'json',
        icon: '🔌',
        description: 'MCP server configuration',
        jsonPath: 'mcpServers',
      },
      {
        label: 'Memory',
        path: '~/.qwen/QWEN.md',
        format: 'md',
        icon: '📝',
        description: 'Global context/memory file',
      },
    ],
  },
];
